/**
@license
Copyright 2018 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {css} from 'lit-element';
/**
 !Note: This file is autogenerated and any changes here may be silently overridden
*/
export const style = css`exmg-grid{--exmg-theme-table-surface: #ffffff;--exmg-theme-table-on-surface: #02182b;--exmg-theme-table-on-surface-disabled: rgba(2, 24, 43, 0.38);--exmg-theme-table-on-surface-low: rgba(2, 24, 43, 0.2);--exmg-table-box-shadow: 0px 1px 5px 0px rgba(2, 24, 43, 0.2), 0px 2px 2px 0px rgba(2, 24, 43, 0.14), 0px 3px 1px -2px rgba(2, 24, 43, 0.12);--exmg-table-row-divider-color: rgba(2, 24, 43, 0.13);--exmg-table-row-selected-background-color: rgba(0, 112, 219, 0.15);--exmg-table-row-selected-color: #02182b;--exmg-table-row-hover-color: #02182b;--exmg-table-row-hover-background-color: rgba(0, 112, 219, 0.25);--exmg-table-rows-expanded-background-color: rgba(0, 112, 219, 0.15);--exmg-table-rows-expanded-color: #02182b;--exmg-table-th-color: rgba(0, 112, 219, 0.6);--exmg-table-th-sortable-hover-color: rgba(2, 24, 43, 0.35);--mdc-theme-primary: #0070db;--exmg-theme-primary: #0070db;--mdc-theme-secondary: #0070db;--exmg-theme-secondary: #0070db;--mdc-theme-on-surface: #02182b;--exmg-theme-on-surface: #02182b;--mdc-theme-surface: #ffffff;--exmg-theme-surface: #ffffff;--mdc-theme-background: transparent;--exmg-theme-background: transparent;--mdc-theme-on-background: #02182b;--exmg-theme-on-background: #02182b;--mdc-theme-disabled: rgba(2, 24, 43, 0.38);--exmg-theme-disabled: rgba(2, 24, 43, 0.38);--exmg-grid-toolbar-setting-list-item-active-bg-color: rgba(0, 112, 219, 0.9);--exmg-grid-toolbar-filter-item-active-bg-color: rgba(0, 112, 219, 0.13);--exmg-table-row-dragged-background-color: #f1f1f1;--exmg-table-rows-expanded-divider-border: none;--exmg-grid-setting-checkbox-bg-color: #0070db }`;
export default style;
