
  // Please do not edit. This file is auto generated by scripts/parseElement.js
  export type Element = {
    name: string;
    version: string;
    url: string;
  };
  export const elements: Element[] = [
    {
      name: '@exmg/exmg-base',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-base',
    },{
      name: '@exmg/exmg-button',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-button',
    },{
      name: '@exmg/exmg-cli',
      version: '8.1.9',
      url: 'https://www.npmjs.com/package/@exmg/exmg-cli',
    },{
      name: '@exmg/exmg-dialogs',
      version: '8.1.15',
      url: 'https://www.npmjs.com/package/@exmg/exmg-dialogs',
    },{
      name: '@exmg/exmg-form',
      version: '8.1.15',
      url: 'https://www.npmjs.com/package/@exmg/exmg-form',
    },{
      name: '@exmg/exmg-grid',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-grid',
    },{
      name: '@exmg/exmg-markdown-editor',
      version: '8.1.15',
      url: 'https://www.npmjs.com/package/@exmg/exmg-markdown-editor',
    },{
      name: '@exmg/exmg-radio-group',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-radio-group',
    },{
      name: '@exmg/exmg-sidemenu',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-sidemenu',
    },{
      name: '@exmg/exmg-sortable',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-sortable',
    },{
      name: '@exmg/exmg-tooltip',
      version: '8.1.14',
      url: 'https://www.npmjs.com/package/@exmg/exmg-tooltip',
    },
  ];
